Server.create(name:"server1", number: 150)
station = Station.create!(name:  "Demo Pod", number: 67,serial_number:  "67150", server_id:  1, type:  "AQMeshPod", active:  true, external:  true, latitude:  52.20025, longitude:-1.72225, city: "London", country: "UK"  )

roleAdmin = Role.create!(name: "Admin")
roleClient = Role.create!(name: "Client")
RoleGroup.create!(name: "demoAdmin", role_id: roleAdmin.id, station_id: station.id)
RoleGroup.create!(name: "demoClient", role_id: roleClient.id, station_id: station.id)

User.create!(email: "mirzalazuardi@gmail.com", password: '12345678', role_id: roleAdmin.id)
User.create!(email: "dennygraph@gmail.com", password: '12345678', role_id: roleClient.id)
#Sensor.create!(name: '', label: 'AETH_ZEROGP')
#Sensor.create!(name: '0.25 um', label: 'GRIMMBIN1')
#Sensor.create!(name: '0.28 um', label: 'GRIMMBIN2')
#Sensor.create!(name: '0.3 um', label: 'GRIMMBIN3')
#Sensor.create!(name: '0.35 um', label: 'GRIMMBIN4')
#Sensor.create!(name: '0.4 um', label: 'GRIMMBIN5')
#Sensor.create!(name: '0.45 um', label: 'GRIMMBIN6')
#Sensor.create!(name: '0.5 um', label: 'GRIMMBIN7')
#Sensor.create!(name: '0.58 um', label: 'GRIMMBIN8')
#Sensor.create!(name: '0.65 um', label: 'GRIMMBIN9')
#Sensor.create!(name: '0.7 um', label: 'GRIMMBIN10')
#Sensor.create!(name: '0.8 um', label: 'GRIMMBIN11')
#Sensor.create!(name: '1 um', label: 'GRIMMBIN12')
#Sensor.create!(name: '1.3 um', label: 'GRIMMBIN13')
#Sensor.create!(name: '1.6 um', label: 'GRIMMBIN14')
#Sensor.create!(name: '10 um', label: 'GRIMMBIN24')
#Sensor.create!(name: '12.5 um', label: 'GRIMMBIN25')
#Sensor.create!(name: '15 um', label: 'GRIMMBIN26')
#Sensor.create!(name: '17.5 um', label: 'GRIMMBIN27')
#Sensor.create!(name: '2.0 um', label: 'GRIMMBIN15')
#Sensor.create!(name: '2.5 um', label: 'GRIMMBIN16')
#Sensor.create!(name: '20 um', label: 'GRIMMBIN28')
#Sensor.create!(name: '25 um', label: 'GRIMMBIN29')
#Sensor.create!(name: '3 um', label: 'GRIMMBIN17')
#Sensor.create!(name: '3.5 um', label: 'GRIMMBIN18')
#Sensor.create!(name: '30 um', label: 'GRIMMBIN30')
#Sensor.create!(name: '32 um', label: 'GRIMMBIN31')
#Sensor.create!(name: '4 um', label: 'GRIMMBIN19')
#Sensor.create!(name: '5 um', label: 'GRIMMBIN20')
#Sensor.create!(name: '6.5 um', label: 'GRIMMBIN21')
#Sensor.create!(name: '7.5 um', label: 'GRIMMBIN22')
#Sensor.create!(name: '8.5 um', label: 'GRIMMBIN23')
#Sensor.create!(name: '85 Percentile Speed', label: 'UND_PERCSPEED')
#Sensor.create!(name: 'AE Tape Remaining (Percent)', label: 'AETH_TAPE')
#Sensor.create!(name: 'AE33 Tape Advanced Count', label: 'AE33_TAPE_COUNT')
#Sensor.create!(name: 'Absolute Air Pressure', label: 'ABSAIRPRESS')
#Sensor.create!(name: 'Absolute Humidity', label: 'ABSOLUTEHUM')
#Sensor.create!(name: 'Absolute Precipitation  (inches)', label: 'PRECQUANABSIN')
#Sensor.create!(name: 'Absolute Precipitation  (mm)', label: 'PRECQUANABSMM')
#Sensor.create!(name: 'Absolute Precipitation (l/m2)', label: 'PRECQUANABSLM')
#Sensor.create!(name: 'Actual Conductivity', label: 'CONDUCACTUAL')
#Sensor.create!(name: 'Actual Flow', label: 'ACTUAL')
#Sensor.create!(name: 'Air Density', label: 'AIRDENSITY')
#Sensor.create!(name: 'Air Pressure', label: 'AIRPRES')
#Sensor.create!(name: 'Air Pressure', label: 'AP')
#Sensor.create!(name: 'Air Temp', label: 'FDMST2')
#Sensor.create!(name: 'Ambient Temp Of Camera', label: 'TCTEMP')
#Sensor.create!(name: 'Ammonia', label: 'NH3')
#Sensor.create!(name: 'Approximate Flow Rate', label: 'APPFLOW')
#Sensor.create!(name: 'Auxilary F', label: 'AUXF')
#Sensor.create!(name: 'Auxiliary A', label: 'AUXA')
#Sensor.create!(name: 'Auxiliary B', label: 'AUXB')
#Sensor.create!(name: 'Auxiliary C', label: 'AUXC')
#Sensor.create!(name: 'Auxiliary D', label: 'AUXD')
#Sensor.create!(name: 'Auxiliary E', label: 'AUXE')
#Sensor.create!(name: 'Auxiliary G', label: 'AUXG')
#Sensor.create!(name: 'Auxilliary Flow', label: 'FDMSAF')
#Sensor.create!(name: 'Average Speed Of All Cars (L1)', label: 'L1ACAR')
#Sensor.create!(name: 'Average Speed Of All Cars (L2)', label: 'L2ACAR')
#Sensor.create!(name: 'Average Speed Of All Cars (L4)', label: 'L4ACAR')
#Sensor.create!(name: 'Average Speed Of All Motor Vehicles (L1)', label: 'L1AMV')
#Sensor.create!(name: 'Average Speed Of All Motor Vehicles (L2)', label: 'L2AMV')
#Sensor.create!(name: 'Average Speed Of All Motor Vehicles (L3)', label: 'L3AMV')
#Sensor.create!(name: 'Average Speed Of All Motor Vehicles (L4)', label: 'L4AMV')
#Sensor.create!(name: 'Average Speed Of All Trucks (L1)', label: 'L1ATRUCK')
#Sensor.create!(name: 'Average Speed Of All Trucks (L2)', label: 'L2ATRUCK')
#Sensor.create!(name: 'Average Speed Of All Trucks (L3)', label: 'L3ATRUCK')
#Sensor.create!(name: 'Average Speed Of All Trucks (L4)', label: 'L4ATRUCK')
#Sensor.create!(name: 'Average Speed Of Cars (L3)', label: 'L3ACAR')
#Sensor.create!(name: 'Average Speed', label: 'UND_AVESPEED')
#Sensor.create!(name: 'Benzene', label: 'BENZENE')
#Sensor.create!(name: 'Bike 85 Percentile Speed', label: 'BIKE_PRECSPEED')
#Sensor.create!(name: 'Bike Average Speed', label: 'BIKE_AVESPEED')
#Sensor.create!(name: 'Bike Gap', label: 'BIKE_GAP')
#Sensor.create!(name: 'Bike Headway', label: 'BIKE_HEADWAY')
#Sensor.create!(name: 'Bike Occupancy', label: 'BIKE_OCCUPANCY')
#Sensor.create!(name: 'Bike Volumn', label: 'BIKE_VOLUMN')
#Sensor.create!(name: 'Black Carbon (PM 10)', label: 'PM10BC')
#Sensor.create!(name: 'Black Carbon (PM 2.5)', label: 'PM25BC')
#Sensor.create!(name: 'Blue Attenuation', label: 'AETH_BLUE_ATTEN')
#Sensor.create!(name: 'Blue SP1', label: 'AETH_BLUESP1')
#Sensor.create!(name: 'Blue SP2', label: 'AETH_BLUESP2')
#Sensor.create!(name: 'Blue', label: 'AETH_BLUE')
#Sensor.create!(name: 'Bypass Flow (Volumetric)', label: 'BYPASS_FLOW')
#Sensor.create!(name: 'CO Cell Temp', label: 'COCT')
#Sensor.create!(name: 'CO Sample Flow', label: 'COSF')
#Sensor.create!(name: 'CO Source Intensity', label: 'COSI')
#Sensor.create!(name: 'CO2 SD', label: 'CO2SD')
#Sensor.create!(name: 'Cap Temp', label: 'FDMST3')
#Sensor.create!(name: 'Car 85 Percentile Speed', label: 'CAR_PRECSPEED')
#Sensor.create!(name: 'Car Average Speed', label: 'CAR_AVESPEED')
#Sensor.create!(name: 'Car Gap', label: 'CAR_GAP')
#Sensor.create!(name: 'Car Headway', label: 'CAR_HEADWAY')
#Sensor.create!(name: 'Car Length (L1)', label: 'L1CLENGTH')
#Sensor.create!(name: 'Car Length (L2)', label: 'L2CLENGTH')
#Sensor.create!(name: 'Car Length (L3)', label: 'L3CLENGTH')
#Sensor.create!(name: 'Car Length (L4)', label: 'L4CLENGTH')
#Sensor.create!(name: 'Car Occupancy', label: 'CAR_OCCUPANCY')
#Sensor.create!(name: 'Car Volumn', label: 'CAR_VOLUMN')
#Sensor.create!(name: 'Carbon Dioxcide', label: 'CO2')
#Sensor.create!(name: 'Carbon Monoxide', label: 'CO')
#Sensor.create!(name: 'Case Temp', label: 'FDMST1')
#Sensor.create!(name: 'Cell Pressure SD', label: 'CELLPRESSURESD')
#Sensor.create!(name: 'Cell Pressure', label: 'CELLPRESSURE')
#Sensor.create!(name: 'Cell Pressure', label: 'CELL_PRESS')
#Sensor.create!(name: 'Cell Temp SD', label: 'CELLTEMPSD')
#Sensor.create!(name: 'Cell Temp', label: 'CELLTEMP')
#Sensor.create!(name: 'Cell Temp', label: 'CELL_TEMP')
#Sensor.create!(name: 'Chlorine', label: 'CL')
#Sensor.create!(name: 'Coincidence', label: 'COINCIDENCE')
#Sensor.create!(name: 'Compass Heading', label: 'COMPASHEAD')
#Sensor.create!(name: 'Conc', label: 'CONC')
#Sensor.create!(name: 'Cooled Filter Temp', label: 'COOLED_FILTER')
#Sensor.create!(name: 'Current Diffusion', label: 'DIFFCURRENT')
#Sensor.create!(name: 'Current Elec Comp Temp', label: 'PSLCECT')
#Sensor.create!(name: 'Current Filter Temp 1', label: 'PSLCFT1')
#Sensor.create!(name: 'Current Flow 1 (Standard)', label: 'PSLCF1S')
#Sensor.create!(name: 'Current Flow 1 (Volumetric)', label: 'PSLCF1V')
#Sensor.create!(name: 'Current Value Position', label: 'VALUE_POS')
#Sensor.create!(name: 'Delta Temp', label: 'DELTATEMP')
#Sensor.create!(name: 'Desired Value Position', label: 'VALUE_POS_DESIRED')
#Sensor.create!(name: 'Device Temp (Inside)', label: 'DEVTEMP')
#Sensor.create!(name: 'Dew Point Temp', label: 'TEMPDEW')
#Sensor.create!(name: 'Dew Point', label: 'DP')
#Sensor.create!(name: 'Dichot Mass Conc', label: 'TEOMAB_DMC')
#Sensor.create!(name: 'Dichot Mass Conc', label: 'TEOMAB_DTM')
#Sensor.create!(name: 'Dichot Reference Mass Conc', label: 'TEOMAB_DRM')
#Sensor.create!(name: 'Differential Precipitation  (inches)', label: 'PRECQUANDIFIN')
#Sensor.create!(name: 'Differential Precipitation  (l/m2)', label: 'PRECQUANDIFLM')
#Sensor.create!(name: 'Differential Precipitation  (mm)', label: 'PRECQUANDIFMM')
#Sensor.create!(name: 'Dimethyldisulphide', label: 'DIMETHYL')
#Sensor.create!(name: 'Ditchot Base Mass Conc', label: 'TEOMAB_DBM')
#Sensor.create!(name: 'Drizzle', label: 'PWSDRIZZLE')
#Sensor.create!(name: 'Dry CO2 SD', label: 'CO2DSD')
#Sensor.create!(name: 'Dry CO2', label: 'CO2D')
#Sensor.create!(name: 'Dry Methane SD', label: 'CH4DSD')
#Sensor.create!(name: 'Dry Methane', label: 'CH4D')
#Sensor.create!(name: 'Dryer Temp', label: 'TEOMA_DD')
#Sensor.create!(name: 'Electricity', label: 'ELECTRICITY')
#Sensor.create!(name: 'Enclosure Temp', label: 'ENCLOSTEMP')
#Sensor.create!(name: 'Error Flag', label: 'ERROR')
#Sensor.create!(name: 'Error Flag', label: 'ERRORFLAG')
#Sensor.create!(name: 'Ethylbenzene', label: 'ETHYLEBENZENE')
#Sensor.create!(name: 'Ethylmercaptan', label: 'ETHYL')
#Sensor.create!(name: 'Filter Life', label: 'FDMSFIL')
#Sensor.create!(name: 'Filter Number', label: 'FILTER_NUMBER')
#Sensor.create!(name: 'Filter Temp', label: 'FILTERTEMP')
#Sensor.create!(name: 'Flag', label: 'FITFLAG')
#Sensor.create!(name: 'Flow 1', label: 'FLOW1')
#Sensor.create!(name: 'Flow 2', label: 'FLOW2')
#Sensor.create!(name: 'Flow C', label: 'FLOWC')
#Sensor.create!(name: 'Flow', label: 'FLOW')
#Sensor.create!(name: 'Freezing Drizzle', label: 'PWSFRDRIZZLE')
#Sensor.create!(name: 'Freezing Rain', label: 'PWSFREEZERAIN')
#Sensor.create!(name: 'Frequency', label: 'FDMSTFREQ')
#Sensor.create!(name: 'Gap Between Vehicles (L1)', label: 'L1GAP')
#Sensor.create!(name: 'Gap Between Vehicles (L2)', label: 'L2GAP')
#Sensor.create!(name: 'Gap Between Vehicles (L3)', label: 'L3GAP')
#Sensor.create!(name: 'Gap Between Vehicles (L4)', label: 'L4GAP')
#Sensor.create!(name: 'Gap', label: 'UND_GAP')
#Sensor.create!(name: 'Graupel', label: 'GRAUPEL')
#Sensor.create!(name: 'Green Attenuation', label: 'AETH_GREEN_ATTEN')
#Sensor.create!(name: 'Green SP1', label: 'AETH_GREENSP1')
#Sensor.create!(name: 'Green SP2', label: 'AETH_GREENSP2')
#Sensor.create!(name: 'Green', label: 'AETH_GREEN')
#Sensor.create!(name: 'Hail', label: 'HAIL')
#Sensor.create!(name: 'Headway', label: 'UND_HEADWAY')
#Sensor.create!(name: 'Humidity I', label: 'HUMI')
#Sensor.create!(name: 'Humidity X', label: 'HUMX')
#Sensor.create!(name: 'Humidity', label: 'HUM')
#Sensor.create!(name: 'Hydrogen Chloride', label: 'HCL')
#Sensor.create!(name: 'Hydrogen Sulphide', label: 'H2S')
#Sensor.create!(name: 'IADS Temp', label: 'IADSTEMP')
#Sensor.create!(name: 'IR1 Attenuation', label: 'AETH_IR1BC')
#Sensor.create!(name: 'IR1 Attenuation', label: 'AETH_IR1BC_ATTEN')
#Sensor.create!(name: 'IR1 SP1', label: 'AETH_IR1SP1')
#Sensor.create!(name: 'IR1 SP2', label: 'AETH_IR1SP2')
#Sensor.create!(name: 'IR2 Attenuation', label: 'AETH_IR2_ATTEN')
#Sensor.create!(name: 'IR2 SP1', label: 'AETH_IR2SP1')
#Sensor.create!(name: 'IR2 SP2', label: 'AETH_IR2SP2')
#Sensor.create!(name: 'Ice Pellets', label: 'ICEPELLETS')
#Sensor.create!(name: 'Infra Red', label: 'AETH_IR2')
#Sensor.create!(name: 'Inside Cabinet Temp', label: 'INCAB_TEMP')
#Sensor.create!(name: 'Intencity Of Light On Sensors', label: 'TCINTENS')
#Sensor.create!(name: 'Internal Pump Current', label: 'INTPUMP')
#Sensor.create!(name: 'LED Temp', label: 'LEDLAMP')
#Sensor.create!(name: 'LHg Mercury Above Last To Be Used', label: 'MERCURY')
#Sensor.create!(name: 'Lamp Flow Rate', label: 'LAMP_FLOWR')
#Sensor.create!(name: 'Lamp Pressure', label: 'LAMP_PRESS')
#Sensor.create!(name: 'Lamp Temp', label: 'LAMP_TEMP')
#Sensor.create!(name: 'Laser Dirty Window', label: 'LASERDIRT')
#Sensor.create!(name: 'Long Term Radon Decay', label: 'LTRD')
#Sensor.create!(name: 'Lower Dirty Window', label: 'LOWDIRT')
#Sensor.create!(name: 'Lower Internal Detector Temp', label: 'LOWDET')
#Sensor.create!(name: 'Lower Internal LED Temp', label: 'LOWLEDT')
#Sensor.create!(name: 'Lung Deposited Surface Area', label: 'LDSA')
#Sensor.create!(name: 'MIU Flag', label: 'MIUFLAG')
#Sensor.create!(name: 'Main Sample Flow', label: 'MAINSF')
#Sensor.create!(name: 'Mass Conc (Hourly)', label: 'FDMSMCH')
#Sensor.create!(name: 'Mass Conc', label: 'FDMSMC')
#Sensor.create!(name: 'Mass Conc', label: 'MC')
#Sensor.create!(name: 'Maximum Wind Speed', label: 'MAXWIND')
#Sensor.create!(name: 'Media', label: 'MEDIA')
#Sensor.create!(name: 'Metaxylene', label: 'M_XYLENE')
#Sensor.create!(name: 'Methane SD', label: 'CH4SD')
#Sensor.create!(name: 'Methane', label: 'CH4')
#Sensor.create!(name: 'Methylmercaptan', label: 'METHYL')
#Sensor.create!(name: 'Mixing Ratio', label: 'MIXINGRATIO')
#Sensor.create!(name: 'Modus', label: 'MODUS')
#Sensor.create!(name: 'Monochromator Flow Rate', label: 'MONO_FLOWR')
#Sensor.create!(name: 'Monochromator Pressure', label: 'MONO_PRESS')
#Sensor.create!(name: 'Monochromator Temp', label: 'MONO_TEMP')
#Sensor.create!(name: 'Motor Temp Of Air Sampler', label: 'ASMT')
#Sensor.create!(name: 'NOX Converter Temp', label: 'NOXCT')
#Sensor.create!(name: 'NOX Oven Temp', label: 'NOXOT')
#Sensor.create!(name: 'NOX Ozone Flow', label: 'O3F')
#Sensor.create!(name: 'NOX Photmultiplier Temp', label: 'NOXPMT')
#Sensor.create!(name: 'NOX Sample Flow', label: 'NOXSF')
#Sensor.create!(name: 'Naphthalene', label: 'NAPHTHALENE')
#Sensor.create!(name: 'Nitric Oxide', label: 'NO')
#Sensor.create!(name: 'Nitrogen Dioxide', label: 'NO2')
#Sensor.create!(name: 'Nitrogen Oxides', label: 'NOx')
#Sensor.create!(name: 'Noise Level', label: 'NOISELEVEL')
#Sensor.create!(name: 'Noise Peak', label: 'NOISEPEAK')
#Sensor.create!(name: 'Non Methane HC', label: 'NMHC')
#Sensor.create!(name: 'Obukhov Length', label: 'OL_LENGTH')
#Sensor.create!(name: 'Occupancy', label: 'UND_OCCUPANY')
#Sensor.create!(name: 'Operating Mode', label: 'FDMS0M')
#Sensor.create!(name: 'Orifice Label', label: 'OT')
#Sensor.create!(name: 'Orthaxylene', label: 'O_XYLENE')
#Sensor.create!(name: 'Outside Cabinet Temp', label: 'OUTCAB_TEMP')
#Sensor.create!(name: 'Oxygen', label: 'O2')
#Sensor.create!(name: 'Ozone Cell Temp', label: 'O3CT')
#Sensor.create!(name: 'Ozone Lamp Intensity', label: 'O3SI')
#Sensor.create!(name: 'Ozone Sample Flow', label: 'O3SF')
#Sensor.create!(name: 'Ozone', label: 'O3')
#Sensor.create!(name: 'PM 10 Filter', label: 'PM10FIL')
#Sensor.create!(name: 'PM 4', label: 'PM4')
#Sensor.create!(name: 'PM10 Air Temp', label: 'PM10FDMST2')
#Sensor.create!(name: 'PM10 Air Temp', label: 'PM10T2')
#Sensor.create!(name: 'PM10 Ambeint RH', label: 'PM10FDMSARH')
#Sensor.create!(name: 'PM10 Ambient Dewpoint', label: 'PM10FDMSADP')
#Sensor.create!(name: 'PM10 Auxiliiary Flow', label: 'PM10AF')
#Sensor.create!(name: 'PM10 Auxilliary Flow', label: 'PM10FDMSAF')
#Sensor.create!(name: 'PM10 Bass Mass', label: 'PM10BM')
#Sensor.create!(name: 'PM10 Cap Temp', label: 'PM10FDMST3')
#Sensor.create!(name: 'PM10 Cap Temp', label: 'PM10T3')
#Sensor.create!(name: 'PM10 Case Temp', label: 'PM10FDMST1')
#Sensor.create!(name: 'PM10 Case Temp', label: 'PM10T1')
#Sensor.create!(name: 'PM10 Filter', label: 'PM10FDMSFIL')
#Sensor.create!(name: 'PM10 Frequency', label: 'PM10FDMSFREQ')
#Sensor.create!(name: 'PM10 Frequency', label: 'PM10FREQ')
#Sensor.create!(name: 'PM10 Mass Conc Hourly', label: 'PM10MCH')
#Sensor.create!(name: 'PM10 Mass Conc Hourly', label: 'PM10MCHR')
#Sensor.create!(name: 'PM10 Mass Conc', label: 'PM10FDMSMC')
#Sensor.create!(name: 'PM10 Operating Mode', label: 'PM10FDMSMODE')
#Sensor.create!(name: 'PM10 Operating `Mode', label: 'PM10M')
#Sensor.create!(name: 'PM10 Reference Mass', label: 'PM10RM')
#Sensor.create!(name: 'PM10 Sample Dewpoint', label: 'PM10FDMSSDP')
#Sensor.create!(name: 'PM10 Sample Flow', label: 'PM10FDMSSF')
#Sensor.create!(name: 'PM10 Sample Flow', label: 'PM10SF')
#Sensor.create!(name: 'PM10 Signal Noise', label: 'PM10FDMSNOISE')
#Sensor.create!(name: 'PM10 Signal Noise', label: 'PM10NOISE')
#Sensor.create!(name: 'PM10 Total Mass', label: 'PM10FDMSTM')
#Sensor.create!(name: 'PM10 Total Mass', label: 'PM10TM')
#Sensor.create!(name: 'PM2.5 Air Temp', label: 'PM25FDMST2')
#Sensor.create!(name: 'PM2.5 Air Temp', label: 'PM25T2')
#Sensor.create!(name: 'PM2.5 Ambient Dew Point', label: 'PM25FDMSADP')
#Sensor.create!(name: 'PM2.5 Ambient RH', label: 'PM25FDMSARH')
#Sensor.create!(name: 'PM2.5 Auxiliiary Flow', label: 'PM25AF')
#Sensor.create!(name: 'PM2.5 Auxilliary Flow', label: 'PM25FDMSAF')
#Sensor.create!(name: 'PM2.5 Base Mass', label: 'PM25BM')
#Sensor.create!(name: 'PM2.5 Cap Temp', label: 'PM25FDMST3')
#Sensor.create!(name: 'PM2.5 Case Temp', label: 'PM25FDMST1')
#Sensor.create!(name: 'PM2.5 Case Temp', label: 'PM25T1')
#Sensor.create!(name: 'PM2.5 Case Temp', label: 'PM25T3')
#Sensor.create!(name: 'PM2.5 Filter', label: 'PM25FDMSFIL')
#Sensor.create!(name: 'PM2.5 Filter', label: 'PM25FIL')
#Sensor.create!(name: 'PM2.5 Frequency', label: 'PM25FDMSFREQ')
#Sensor.create!(name: 'PM2.5 Frequency', label: 'PM25FREQ')
#Sensor.create!(name: 'PM2.5 Mass Conc Hourly', label: 'PM25MCH')
#Sensor.create!(name: 'PM2.5 Mass Conc Hourly', label: 'PM25MCHR')
#Sensor.create!(name: 'PM2.5 Mass Conc', label: 'PM25FDMSMC')
#Sensor.create!(name: 'PM2.5 Mode', label: 'PM25MODE')
#Sensor.create!(name: 'PM2.5 Operating Mode', label: 'PM25FDMSMODE')
#Sensor.create!(name: 'PM2.5 Reference Mass', label: 'PM25RM')
#Sensor.create!(name: 'PM2.5 Sample Dew Point', label: 'PM25FDMSSDP')
#Sensor.create!(name: 'PM2.5 Sample Flow', label: 'PM25FDMSSF')
#Sensor.create!(name: 'PM2.5 Sample Flow', label: 'PM25SF')
#Sensor.create!(name: 'PM2.5 Signal Noise', label: 'PM25FDMSNOISE')
#Sensor.create!(name: 'PM2.5 Signal Noise', label: 'PM25NOISE')
#Sensor.create!(name: 'PM2.5 Total Mass', label: 'PM25FDMSTM')
#Sensor.create!(name: 'PM2.5 Total Mass', label: 'PM25TM')
#Sensor.create!(name: 'Paraxylene', label: 'P_XYLENE')
#Sensor.create!(name: 'Particle Count', label: 'PARTICLE_COUNT')
#Sensor.create!(name: 'Particle Total Count', label: 'PARTIC')
#Sensor.create!(name: 'Particulate Elemental Carbon', label: 'PEC')
#Sensor.create!(name: 'Particulate Matter (PM 1)', label: 'PM1')
#Sensor.create!(name: 'Particulate Matter (PM 10)', label: 'PM10')
#Sensor.create!(name: 'Particulate Matter (PM 2.5)', label: 'PM25')
#Sensor.create!(name: 'Particulate Matter (Total)', label: 'PMTOTAL')
#Sensor.create!(name: 'Particulate Nitrate', label: 'PN')
#Sensor.create!(name: 'Particulate Organic Carbon', label: 'POC')
#Sensor.create!(name: 'Particulate Sulphate', label: 'PS')
#Sensor.create!(name: 'Particulate Total Carbon', label: 'PTC')
#Sensor.create!(name: 'Pedestrian 85 Percentile Speed', label: 'PED_PRECSPEED')
#Sensor.create!(name: 'Pedestrian Average Speed', label: 'PED_AVESPEED')
#Sensor.create!(name: 'Pedestrian Gap', label: 'PED_GAP')
#Sensor.create!(name: 'Pedestrian Headway', label: 'PED_HEADWAY')
#Sensor.create!(name: 'Pedestrian Occupancy', label: 'PED_OCCUPANCY')
#Sensor.create!(name: 'Pedestrian Volumn', label: 'PED_VOLUMN')
#Sensor.create!(name: 'Precipitation Accumulation', label: 'RAIFLACC')
#Sensor.create!(name: 'Precipitation Intensity (inches/h)', label: 'PRECINTIMH')
#Sensor.create!(name: 'Precipitation Intensity (l/m2/h)', label: 'PRECINTLMH')
#Sensor.create!(name: 'Precipitation Intensity (mm/h)', label: 'PRECINTMMH')
#Sensor.create!(name: 'Precipitation Intensity', label: 'PERCINT')
#Sensor.create!(name: 'Precipitation Intensity', label: 'RAIFLINT')
#Sensor.create!(name: 'Precipitation Type', label: 'PERCTYPE')
#Sensor.create!(name: 'Pressure From Sampler', label: 'ASPR')
#Sensor.create!(name: 'Pressure PA', label: 'PRESSUREPA')
#Sensor.create!(name: 'Pump Temp', label: 'PUMP')
#Sensor.create!(name: 'RD0 SD', label: 'RD0SD')
#Sensor.create!(name: 'RD0', label: 'RD0')
#Sensor.create!(name: 'RD1 SD', label: 'RD1SD')
#Sensor.create!(name: 'RD1', label: 'RD1')
#Sensor.create!(name: 'Rain Detected', label: 'RAINDECTED')
#Sensor.create!(name: 'Rain Fall', label: 'RAIN')
#Sensor.create!(name: 'Raw Channel Deviation', label: 'RAWCHANDEV')
#Sensor.create!(name: 'Raw Electrometer Value', label: 'RAWELECTRO')
#Sensor.create!(name: 'Red Attenuation', label: 'AETH_RED_ATTEN')
#Sensor.create!(name: 'Red SP1', label: 'AETH_REDSP1')
#Sensor.create!(name: 'Red SP2', label: 'AETH_REDSP2')
#Sensor.create!(name: 'Red', label: 'AETH_RED')
#Sensor.create!(name: 'Ref Mass Conc', label: 'TEOMB_RM')
#Sensor.create!(name: 'Reference', label: 'REF')
#Sensor.create!(name: 'Relative Air Pressure', label: 'RELAIRPRESS')
#Sensor.create!(name: 'Relative Humidity (Inside)', label: 'RELHUM')
#Sensor.create!(name: 'SO2 Cell Temp', label: 'SO2CT')
#Sensor.create!(name: 'SO2 Lamp Intensity', label: 'SO2LAMPINT')
#Sensor.create!(name: 'SO2 Oven Temp', label: 'SO2OT')
#Sensor.create!(name: 'SO2 Sample Flow', label: 'SO2AF')
#Sensor.create!(name: 'Sample Flow', label: 'AETH_SF')
#Sensor.create!(name: 'Sample Flow', label: 'FDMSSF')
#Sensor.create!(name: 'Sampled Filter Temp', label: 'SAMPLED_FILTER')
#Sensor.create!(name: 'Sampled Volumn', label: 'SAMPLED_VOLUMN')
#Sensor.create!(name: 'Sampler (PM 10)', label: 'PM10GRAV')
#Sensor.create!(name: 'Sampler (PM 2.5)', label: 'PM25GRAV')
#Sensor.create!(name: 'Set Point (Flow)', label: 'PSLSPF1')
#Sensor.create!(name: 'Short Term Radon Decay', label: 'STRD')
#Sensor.create!(name: 'Signal Noise', label: 'FDMSNOISE')
#Sensor.create!(name: 'Signal Noise', label: 'TEOMB_N')
#Sensor.create!(name: 'Snow Flakes', label: 'SNOWFLAKES')
#Sensor.create!(name: 'Snow Grains', label: 'SNOWGRAINS')
#Sensor.create!(name: 'Soil Composition (100cm)', label: 'SOIL_COMP_100')
#Sensor.create!(name: 'Soil Composition (10cm)', label: 'SOIL_COMP_10')
#Sensor.create!(name: 'Soil Composition (110cm)', label: 'SOIL_COMP_110')
#Sensor.create!(name: 'Soil Composition (120cm)', label: 'SOIL_COMP_120')
#Sensor.create!(name: 'Soil Composition (130cm)', label: 'SOIL_COMP_130')
#Sensor.create!(name: 'Soil Composition (140cm)', label: 'SOIL_COMP_140')
#Sensor.create!(name: 'Soil Composition (150cm)', label: 'SOIL_COMP_150')
#Sensor.create!(name: 'Soil Composition (160cm)', label: 'SOIL_COMP_160')
#Sensor.create!(name: 'Soil Composition (20cm)', label: 'SOIL_COMP_20')
#Sensor.create!(name: 'Soil Composition (30cm)', label: 'SOIL_COMP_30')
#Sensor.create!(name: 'Soil Composition (40cm)', label: 'SOIL_COMP_40')
#Sensor.create!(name: 'Soil Composition (50cm)', label: 'SOIL_COMP_50')
#Sensor.create!(name: 'Soil Composition (60cm)', label: 'SOIL_COMP_60')
#Sensor.create!(name: 'Soil Composition (70cm)', label: 'SOIL_COMP_70')
#Sensor.create!(name: 'Soil Composition (80cm)', label: 'SOIL_COMP_80')
#Sensor.create!(name: 'Soil Composition (90cm)', label: 'SOIL_COMP_90')
#Sensor.create!(name: 'Soil Salinity (100cm)', label: 'SOIL_SAL_100')
#Sensor.create!(name: 'Soil Salinity (10cm)', label: 'SOIL_SAL_10')
#Sensor.create!(name: 'Soil Salinity (110cm)', label: 'SOIL_SAL_110')
#Sensor.create!(name: 'Soil Salinity (120cm)', label: 'SOIL_SAL_120')
#Sensor.create!(name: 'Soil Salinity (130cm)', label: 'SOIL_SAL_130')
#Sensor.create!(name: 'Soil Salinity (140cm)', label: 'SOIL_SAL_140')
#Sensor.create!(name: 'Soil Salinity (150cm)', label: 'SOIL_SAL_150')
#Sensor.create!(name: 'Soil Salinity (160cm)', label: 'SOIL_SAL_160')
#Sensor.create!(name: 'Soil Salinity (20cm)', label: 'SOIL_SAL_20')
#Sensor.create!(name: 'Soil Salinity (30cm)', label: 'SOIL_SAL_30')
#Sensor.create!(name: 'Soil Salinity (40cm)', label: 'SOIL_SAL_40')
#Sensor.create!(name: 'Soil Salinity (50cm)', label: 'SOIL_SAL_50')
#Sensor.create!(name: 'Soil Salinity (60cm)', label: 'SOIL_SAL_60')
#Sensor.create!(name: 'Soil Salinity (70cm)', label: 'SOIL_SAL_70')
#Sensor.create!(name: 'Soil Salinity (80cm)', label: 'SOIL_SAL_80')
#Sensor.create!(name: 'Soil Salinity (90cm)', label: 'SOIL_SAL_90')
#Sensor.create!(name: 'Soil Temp (100cm)', label: 'SOIL_TEMP_100')
#Sensor.create!(name: 'Soil Temp (10cm)', label: 'SOIL_TEMP_10')
#Sensor.create!(name: 'Soil Temp (110cm)', label: 'SOIL_TEMP_110')
#Sensor.create!(name: 'Soil Temp (120cm)', label: 'SOIL_TEMP_120')
#Sensor.create!(name: 'Soil Temp (130cm)', label: 'SOIL_TEMP_130')
#Sensor.create!(name: 'Soil Temp (140cm)', label: 'SOIL_TEMP_140')
#Sensor.create!(name: 'Soil Temp (150cm)', label: 'SOIL_TEMP_150')
#Sensor.create!(name: 'Soil Temp (160cm)', label: 'SOIL_TEMP_160')
#Sensor.create!(name: 'Soil Temp (20cm)', label: 'SOIL_TEMP_20')
#Sensor.create!(name: 'Soil Temp (30cm)', label: 'SOIL_TEMP_30')
#Sensor.create!(name: 'Soil Temp (40cm)', label: 'SOIL_TEMP_40')
#Sensor.create!(name: 'Soil Temp (50cm)', label: 'SOIL_TEMP_50')
#Sensor.create!(name: 'Soil Temp (60cm)', label: 'SOIL_TEMP_60')
#Sensor.create!(name: 'Soil Temp (70cm)', label: 'SOIL_TEMP_70')
#Sensor.create!(name: 'Soil Temp (80cm)', label: 'SOIL_TEMP_80')
#Sensor.create!(name: 'Soil Temp (90cm)', label: 'SOIL_TEMP_90')
#Sensor.create!(name: 'Solar Radiation', label: 'SOLAR')
#Sensor.create!(name: 'Sound Level Meter (LEQ)', label: 'LEQ')
#Sensor.create!(name: 'Sound Level Meter (Max)', label: 'MAX')
#Sensor.create!(name: 'Sound Level Meter (Min)', label: 'MIN')
#Sensor.create!(name: 'Sound Level Meter (Peak)', label: 'PEAK')
#Sensor.create!(name: 'Sound Level Meter (SEL)', label: 'SEL')
#Sensor.create!(name: 'Sound Level Meter (SPL)', label: 'SPL')
#Sensor.create!(name: 'Stability', label: 'STABIL')
#Sensor.create!(name: 'Standard Flow', label: 'STAND')
#Sensor.create!(name: 'Suction Pump Output', label: 'SUCPUMP')
#Sensor.create!(name: 'Sulphur Dioxide', label: 'SO2')
#Sensor.create!(name: 'Supply Power', label: 'SPOWER')
#Sensor.create!(name: 'System Status', label: 'SYSTEM_STATUS')
#Sensor.create!(name: 'TCR', label: 'TCR')
#Sensor.create!(name: 'TEOM A  Frequency', label: 'TEOMA_F')
#Sensor.create!(name: 'TEOM A Base Mass Conc', label: 'TEOMA_BM')
#Sensor.create!(name: 'TEOM A Cooler Temp', label: 'TEOMA_CT')
#Sensor.create!(name: 'TEOM A Dryer RH', label: 'TEOMA_RH')
#Sensor.create!(name: 'TEOM A Dryer Temp', label: 'TEOMA_DT')
#Sensor.create!(name: 'TEOM A Filter Load', label: 'TEOMA_FL')
#Sensor.create!(name: 'TEOM A Flow Rate', label: 'TEOMA_FR')
#Sensor.create!(name: 'TEOM A Mass Conc', label: 'TEOMA_MC')
#Sensor.create!(name: 'TEOM A Noise', label: 'TEOMA_N')
#Sensor.create!(name: 'TEOM A Reference Mass Conc', label: 'TEOMA_RM')
#Sensor.create!(name: 'TEOM A Total Mass', label: 'TEOMA_TM')
#Sensor.create!(name: 'TEOM B Base Mass Conc', label: 'TEOMB_BM')
#Sensor.create!(name: 'TEOM B Cooler Temp', label: 'TEOMB_CT')
#Sensor.create!(name: 'TEOM B Dryer Dew Point', label: 'TEOMB_DD')
#Sensor.create!(name: 'TEOM B Dryer RH', label: 'TEOMB_RH')
#Sensor.create!(name: 'TEOM B Dryer Temp', label: 'TEOMB_DT')
#Sensor.create!(name: 'TEOM B Filter Load', label: 'TEOMB_FL')
#Sensor.create!(name: 'TEOM B Flow Rate', label: 'TEOMB_FR')
#Sensor.create!(name: 'TEOM B Frequency', label: 'TEOMB_F')
#Sensor.create!(name: 'TEOM B Mass Conc ', label: 'TEOMB_MC')
#Sensor.create!(name: 'TEOM B Total Mass', label: 'TEOMB_TM')
#Sensor.create!(name: 'TSP Air Temp', label: 'TPM10T2')
#Sensor.create!(name: 'TSP Auxilliary Flow', label: 'TPM10AF')
#Sensor.create!(name: 'TSP Cap Temp', label: 'TPM10T3')
#Sensor.create!(name: 'TSP Case Temp', label: 'TPM10T1')
#Sensor.create!(name: 'TSP Filter', label: 'TPM10FIL')
#Sensor.create!(name: 'TSP Frequency', label: 'TPM10FREQ')
#Sensor.create!(name: 'TSP Mass Conc Hourly', label: 'TPM10MCH')
#Sensor.create!(name: 'TSP Mass Conc', label: 'TPM10')
#Sensor.create!(name: 'TSP Operating Mode', label: 'TPM10M')
#Sensor.create!(name: 'TSP Sample Flow', label: 'TPM10SF')
#Sensor.create!(name: 'TSP Sampler', label: 'PMTSPGRAV')
#Sensor.create!(name: 'TSP Signal Noise', label: 'TPM10NOISE')
#Sensor.create!(name: 'TSP Total Mass', label: 'TPM10TM')
#Sensor.create!(name: 'TSP label', label: 'TSP')
#Sensor.create!(name: 'Temp SD', label: 'TEMPSD')
#Sensor.create!(name: 'Temp', label: 'PTEMP')
#Sensor.create!(name: 'Temp', label: 'SIMPLETEMP')
#Sensor.create!(name: 'Temperature', label: 'TEMP')
#Sensor.create!(name: 'Time Run', label: 'TR')
#Sensor.create!(name: 'Toluene', label: 'TOLUENE')
#Sensor.create!(name: 'Total Hydrocarbons', label: 'THC')
#Sensor.create!(name: 'Total Mass', label: 'FDMSTM')
#Sensor.create!(name: 'Total Nitrogen Compounds', label: 'THX_LABEL')
#Sensor.create!(name: 'Total Occupancy (L1)', label: 'L1OCCUP')
#Sensor.create!(name: 'Total Occupancy (L2)', label: 'L2OCCUP')
#Sensor.create!(name: 'Total Occupancy (L3)', label: 'L3OCCUP')
#Sensor.create!(name: 'Total Occupancy (L4)', label: 'L4OCCUP')
#Sensor.create!(name: 'Total Quantity Of Cars (L1)', label: 'L1QCar')
#Sensor.create!(name: 'Total Quantity Of Cars (L2)', label: 'L2QCAR')
#Sensor.create!(name: 'Total Quantity Of Cars (L3)', label: 'L3QCAR')
#Sensor.create!(name: 'Total Quantity Of Cars (L4)', label: 'L4QCAR')
#Sensor.create!(name: 'Total Quantity Of Trucks (L1)', label: 'L1QTRUCK')
#Sensor.create!(name: 'Total Quantity Of Trucks (L2)', label: 'L2QTRUCK')
#Sensor.create!(name: 'Total Quantity Of Trucks (L3)', label: 'L3QTRUCK')
#Sensor.create!(name: 'Total Quantity Of Trucks (L4)', label: 'L4QTRUCK')
#Sensor.create!(name: 'Total Quantity Of Vehicles (L1)', label: 'L1QMV')
#Sensor.create!(name: 'Total Quantity Of Vehicles (L2)', label: 'L2QMV')
#Sensor.create!(name: 'Total Quantity Of Vehicles (L3)', label: 'L3QMV')
#Sensor.create!(name: 'Total Quantity Of Vehicles (L4)', label: 'L4QMV')
#Sensor.create!(name: 'Total Sampled Volume (Standard)', label: 'TSVS')
#Sensor.create!(name: 'Total Sampled Volume', label: 'TSV')
#Sensor.create!(name: 'Truck 85 Percentile Speed', label: 'TRK_PRECSPEED')
#Sensor.create!(name: 'Truck Average Speed', label: 'TRK_AVESPEED')
#Sensor.create!(name: 'Truck Gap', label: 'TRK_GAP')
#Sensor.create!(name: 'Truck Headway', label: 'TRK_HEADWAY')
#Sensor.create!(name: 'Truck Length (L1)', label: 'L1TLENGTH')
#Sensor.create!(name: 'Truck Length (L2)', label: 'L2TLENGTH')
#Sensor.create!(name: 'Truck Length (L3)', label: 'L3TLENGTH')
#Sensor.create!(name: 'Truck Length (L4)', label: 'L4TLENGTH')
#Sensor.create!(name: 'Truck Occupany', label: 'TRK_OCCUPANCY')
#Sensor.create!(name: 'Truck Volumn', label: 'TRK_VOLUMN')
#Sensor.create!(name: 'UV Attenuation', label: 'AETH_UV_ATTEN')
#Sensor.create!(name: 'UV SP1', label: 'AETH_UVSP1')
#Sensor.create!(name: 'UV SP2', label: 'AETH_UVSP2')
#Sensor.create!(name: 'UV', label: 'AETH_UV')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (100cm)', label: 'SOIL_UN_100')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (10cm)', label: 'SOIL_UN_10')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (110cm)', label: 'SOIL_UN_110')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (120cm)', label: 'SOIL_UN_120')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (130cm)', label: 'SOIL_UN_130')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (140cm)', label: 'SOIL_UN_140')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (150cm)', label: 'SOIL_UN_150')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (160cm)', label: 'SOIL_UN_160')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (20cm)', label: 'SOIL_UN_20')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (30cm)', label: 'SOIL_UN_30')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (40cm)', label: 'SOIL_UN_40')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (50cm)', label: 'SOIL_UN_50')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (60cm)', label: 'SOIL_UN_60')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (70cm)', label: 'SOIL_UN_70')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (80cm)', label: 'SOIL_UN_80')
#Sensor.create!(name: 'Un-Compensated Soil Moisture (90cm)', label: 'SOIL_UN_90')
#Sensor.create!(name: 'Unknown Flag', label: 'UNKNOWN')
#Sensor.create!(name: 'Upper Dirty Window', label: 'UPDIRT')
#Sensor.create!(name: 'Upper Internal Detector Temp', label: 'UPDET')
#Sensor.create!(name: 'Upper Internal LED Temp', label: 'UPLEDT')
#Sensor.create!(name: 'Vacume Pump Pressure', label: 'VACCPUMP_PRESS')
#Sensor.create!(name: 'Velocity', label: 'VELOCITY')
#Sensor.create!(name: 'Visibility Range Average > ST', label: 'PWSVIS')
#Sensor.create!(name: 'Visibility Rangle Average >10mins', label: 'PWSVISAV')
#Sensor.create!(name: 'Visibility', label: 'VIS')
#Sensor.create!(name: 'Volatile Organic Carbon', label: 'VOC')
#Sensor.create!(name: 'Volume', label: 'VOLUMN')
#Sensor.create!(name: 'Volumn', label: 'UND_VOLUMN')
#Sensor.create!(name: 'WMO Code', label: 'WNOCODE')
#Sensor.create!(name: 'Water SD', label: 'H20SD')
#Sensor.create!(name: 'Water', label: 'H2O')
#Sensor.create!(name: 'Wet Bulb Temp', label: 'WETBULBTEMP')
#Sensor.create!(name: 'Wet Bulb', label: 'WETBULB')
#Sensor.create!(name: 'Wetness Sensor', label: 'WET')
#Sensor.create!(name: 'Wind Chill Temp', label: 'WNDCHILL')
#Sensor.create!(name: 'Wind Direction SD', label: 'WINDDIRSD')
#Sensor.create!(name: 'Wind Direction', label: 'WD')
#Sensor.create!(name: 'Wind Heater Temp', label: 'WINDHEATTEMP')
#Sensor.create!(name: 'Wind Signal Quality', label: 'WINDSIG')
#Sensor.create!(name: 'Wind Speed (U Component)', label: 'WUCOMP')
#Sensor.create!(name: 'Wind Speed (V Component)', label: 'WVCOMP')
#Sensor.create!(name: 'Wind Speed (W Component)', label: 'WSCOMP')
#Sensor.create!(name: 'Wind Speed (m/s)', label: 'WINDMS')
#Sensor.create!(name: 'Wind Speed (mph)', label: 'WINDMPH')
#Sensor.create!(name: 'Wind Speed SD', label: 'WINDSD')
#Sensor.create!(name: 'Wind Speed', label: 'WS')
#Sensor.create!(name: 'Wind Value Quality', label: 'WINDVALQUAL')
#Sensor.create!(name: 'Xylenes', label: 'XYLENES')
#Sensor.create!(name: 'Yellow Attenuation', label: 'AETH_YELLOW_ATTEN')
#Sensor.create!(name: 'Yellow SP1', label: 'AETH_YELLOWSP1')
#Sensor.create!(name: 'Yellow SP2', label: 'AETH_YELLOWSP2')
#Sensor.create!(name: 'Yellow', label: 'AETH_YELLOW')
#Sensor.create!(name: 'pH Label', label: 'PH')
#Unit.create!(name: 'ATM', unit: 'atm')
#Unit.create!(name: 'Celsius', unit: 'C')
#Unit.create!(name: 'Centigrade', unit: 'C')
#Unit.create!(name: 'Counts per minute', unit: 'cpm')
#Unit.create!(name: 'Cubic Meters Per Hour', unit: 'm3/h')
#Unit.create!(name: 'Cubic Meters', unit: 'm3')
#Unit.create!(name: 'Decibels', unit: 'dB')
#Unit.create!(name: 'Degrees', unit: 'Deg')
#Unit.create!(name: 'Digit', unit: '')
#Unit.create!(name: 'Fahrenheit', unit: 'F')
#Unit.create!(name: 'Feet', unit: 'ft')
#Unit.create!(name: 'GKG', unit: '')
#Unit.create!(name: 'HCMHR', unit: '')
#Unit.create!(name: 'Hectopascals', unit: 'hPa')
#Unit.create!(name: 'Hertz', unit: 'Hz')
#Unit.create!(name: 'Inch', unit: 'In')
#Unit.create!(name: 'KG/M3', unit: 'Kg/m3')
#Unit.create!(name: 'KJKG', unit: '')
#Unit.create!(name: 'Kelvin', unit: 'K')
#Unit.create!(name: 'KiloWattHour', unit: 'KWHr')
#Unit.create!(name: 'Kilometers Per Second', unit: 'kph')
#Unit.create!(name: 'Kilopascals', unit: 'Kpa')
#Unit.create!(name: 'Knots', unit: 'kn')
#Unit.create!(name: 'LM2', unit: '')
#Unit.create!(name: 'LM2H', unit: '')
#Unit.create!(name: 'Liters Per Minute', unit: 'l/min')
#Unit.create!(name: 'MM/DAY', unit: 'mm/day')
#Unit.create!(name: 'MMHR', unit: 'mm/h')
#Unit.create!(name: 'Meters Per Second', unit: 'm/s')
#Unit.create!(name: 'Metres', unit: 'm')
#Unit.create!(name: 'Micrograms Per Cubic Meter', unit: 'ug/m3')
#Unit.create!(name: 'Micrograms', unit: 'ug')
#Unit.create!(name: 'Miles Per Hour', unit: 'mph')
#Unit.create!(name: 'Milimeters', unit: 'mm')
#Unit.create!(name: 'Milligrams Per Cubic Meter', unit: 'mg/m3')
#Unit.create!(name: 'Millileters Per Minute', unit: 'ml/min')
#Unit.create!(name: 'Millimeters Of Mercury', unit: 'mmHg')
#Unit.create!(name: 'Millivolts', unit: 'mV')
#Unit.create!(name: 'Minutes', unit: 'mins')
#Unit.create!(name: 'None', unit: '')
#Unit.create!(name: 'Number', unit: 'Null')
#Unit.create!(name: 'Particles per cm3', unit: 'P/cm3')
#Unit.create!(name: 'Parts Per Billion', unit: 'ppb')
#Unit.create!(name: 'Parts Per Million', unit: 'ppm')
#Unit.create!(name: 'Per Day', unit: '/day')
#Unit.create!(name: 'Per Hour', unit: '/h')
#Unit.create!(name: 'Percent Of Time', unit: '%time')
#Unit.create!(name: 'Percent', unit: '%')
#Unit.create!(name: 'Pressure (bar)', unit: 'bar')
#Unit.create!(name: 'Pressure (mbar)', unit: 'mbar')
#Unit.create!(name: 'Pressure (psi)', unit: 'psi')
#Unit.create!(name: 'Quantity', unit: 'Qty')
#Unit.create!(name: 'Revolutions Per Minute', unit: 'RPM')
#Unit.create!(name: 'Seconds', unit: 's')
#Unit.create!(name: 'Volts', unit: 'V')
#Unit.create!(name: 'WM2', unit: 'W/m2')
#Unit.create!(name: 'grammes per m3', unit: 'g/m3')
#Unit.create!(name: 'nanogramme per meter cubed', unit: 'ng/m3')
